#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 15, 2020 08:55:50 PM JST  platform: Linux


def printa():
    print("aaa")
    #sys.stdout.flush()




